[package]
name = "rust_tusks"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = { version = "0.4.26", features = ["serde"] }
serde = { version = '1.0.171', features = ["derive"] }
serde_json = "1.0.103" 